version: "3.9"
services:
  keycloak:
    build:
      context: ./keycloak
    ports:
      - "8080:8080"
    depends_on:
      - keycloakdb

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  mongo:
    build:
      context: ./mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  simpl.snippet:
    build:
      context: ./simpl.snippet
    ports:
      - "5170:80"
    depends_on:
      - mongo
      - keycloak
      - redis

  simpl.snippet.client:
    build:
      context: ./simpl.snippet.client
    ports:
      - "80:80"
    depends_on:
      - simpl.snippet
    environment:
      - VITE_HOST=0.0.0.0
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_data:
  mongo_data:
